### ISSUE TITLE
No Such module about select !

### ISSUE THREAD

**Issue by guiyang882** [seann999/ssd_tensorflow#5]
```python
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/liuguiyang/Documents/CodeProj/PyProj/ssd_tensorflow/trainer.py
/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
npy file loaded
build model started
build model finished: 0s
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
Traceback (most recent call last):
  File "/Users/liuguiyang/Documents/CodeProj/PyProj/ssd_tensorflow/trainer.py", line 411, in <module>
    evaluate_image(FLAGS.image_path)
  File "/Users/liuguiyang/Documents/CodeProj/PyProj/ssd_tensorflow/trainer.py", line 358, in evaluate_image
    boxes_, confidences_ = get_image_detections(path)
  File "/Users/liuguiyang/Documents/CodeProj/PyProj/ssd_tensorflow/trainer.py", line 345, in get_image_detections
    ssd = SSD()
  File "/Users/liuguiyang/Documents/CodeProj/PyProj/ssd_tensorflow/trainer.py", line 35, in __init__
    model.loss(self.pred_labels, self.pred_locs, total_boxes)
  File "/Users/liuguiyang/Documents/CodeProj/PyProj/ssd_tensorflow/model.py", line 83, in loss
    loc_loss = tf.reduce_sum(smooth_l1(pred_locs - true_locs), reduction_indices=2) * positives
  File "/Users/liuguiyang/Documents/CodeProj/PyProj/ssd_tensorflow/model.py", line 68, in smooth_l1
    re = tf.select(condition, l2, l1)
AttributeError: 'module' object has no attribute 'select'
```

**Comment by guiyang882** [comment]
may be the tensorflow was updated !
When i use 11version, it ok!
